### ISSUE TITLE
Inquiry about 'Effect of Height in Voxel Space' in Sec. 4.2.

### ISSUE THREAD

**Issue by zjwzcx** [dvlab-research/UVTR#10]
Hi Yanwei, thanks for your awesome work! @yanwei-li 

You've showed the effect of height in Table 1, which demonstrated larger height values along axis Z contribute more for camera-based 3d detector. I'm very curious about the performance of camera-based detectors when we set height = 21, 41 or even larger. Have you conducted some experiments with much larger height? Do you have any insight about the setting of height value?

Look forward to your reply!

**Comment by yanwei-li** [comment]
Hi, that's a good question. I did not try such a large height due to the GPU memory constraint. Because the height 11 is actually the same resolution of the voxel grid as that in BEV (~0.2m). I guess the performance could be saturated with a much larger height.

**Comment by zjwzcx** [comment]
> Hi, that's a good question. I did not try such a large height due to the GPU memory constraint. Because the height 11 is actually the same resolution of the voxel grid as that in BEV (~0.2m). I guess the performance could be saturated with a much larger height.

Got it! Thanks for your reply!
