### ISSUE TITLE
Could you give the more detailed structure of nuScenes?

### ISSUE THREAD

**Issue by Like2021** [dvlab-research/UVTR#11]
Thanks for your great work!

but like this:

'nuscenes/samples' and 'nuscenes/sweeps'

I don't know where do these two subfiles come from?

maybe come from all partial V1.0-trainval dataset of nuScenes?

**Comment by yanwei-li** [comment]
Hi, yes, you can download get them from the nuScene website (https://www.nuscenes.org/nuscenes).
