### ISSUE TITLE
CPU memory ran out while running create_data.py

### ISSUE THREAD

**Issue by gw0522** [dvlab-research/UVTR#12]
When “Create GT Database of NuScenesSweepDataset”，the process is killed。。。How can I fix this problem？ Thanks a lot ！！！！

**Comment by yanwei-li** [comment]
Hi, maybe you should provide more memory. For your reference, my previous experiments run with 200GB memory, which runs smoothly.

**Comment by gw0522** [comment]
Thanks for your reply, I solved the problem.
