### ISSUE TITLE
excuese me，create data error

### ISSUE THREAD

**Issue by eezhang123** [dvlab-research/UVTR#15]
environment：
mmcv-full               1.3.8
mmdet                   2.14.0
mmdet3d                 0.17.3          
mmsegmentation          0.14.1
torch1.7.1
cuda 11.0

UVTR/mmdetection3d/mmdet3d/core/bbox/structures/utils.py", line 139, in points_cam2img
    4, device=proj_mat.device, dtype=proj_mat.dtype)
AttributeError: 'numpy.ndarray' object has no attribute 'device'

**Comment by eezhang123** [comment]
train scene: 700, val scene: 150
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 34149/34149, 1.2 task/s, elapsed: 28247s, ETA:     0s
train sample: 28130, val sample: 6019
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 54.895 seconds.
======
Reverse indexing ...
Done reverse indexing in 12.6 seconds.
======
[                                                  ] 0/28130, elapsed: 0s, ETA:Traceback (most recent call last):
File "extra_tools/create_data.py", line 86, in <module>
    max_sweeps=args.max_sweeps)
  File "extra_tools/create_data.py", line 40, in nuscenes_data_prep
    root_path, info_train_path, version=version)

**Comment by eezhang123** [comment]
train scene: 700, val scene: 150
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 34149/34149, 1.2 task/s, elapsed: 28247s, ETA:     0s
train sample: 28130, val sample: 6019
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 54.895 seconds.
======
Reverse indexing ...
Done reverse indexing in 12.6 seconds.
======
[                                                  ] 0/28130, elapsed: 0s, ETA:Traceback (most recent call last):
  File "extra_tools/create_data.py", line 86, in <module>
    max_sweeps=args.max_sweeps)
  File "extra_tools/create_data.py", line 40, in nuscenes_data_prep
    root_path, info_train_path, version=version)

**Comment by eezhang123** [comment]
train scene: 700, val scene: 150
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 34149/34149, 1.2 task/s, elapsed: 28247s, ETA:     0s
train sample: 28130, val sample: 6019

======
[                                                  ] 0/28130, elapsed: 0s, ETA:Traceback (most recent call last):
  File "extra_tools/create_data.py", line 86, in <module>
    max_sweeps=args.max_sweeps)
  File "extra_tools/create_data.py", line 40, in nuscenes_data_prep
    root_path, info_train_path, version=version)

**Comment by yanwei-li** [comment]
Thanks for this report! I think a naive solution is directly commenting these lines. Because the 2D annotation conversion is actually not used in our experiments. I update the code. Please try it again.
