### ISSUE TITLE
Results based on distance

### ISSUE THREAD

**Issue by konyul** [dvlab-research/UVTR#16]
I see you report the performance with different distances, how did you get results on different distances??

**Comment by yanwei-li** [comment]
Hi, you can filter the predicted box and annotation according to the distance in the evaluation script, like the function here https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/evaluate.py#L94

**Comment by konyul** [comment]
thank you for the reply!!
