### ISSUE TITLE
nuscene preprocess

### ISSUE THREAD

**Issue by GondorFu** [dvlab-research/UVTR#19]
It takes a long time on my device for preprocess nuscene dataset. Can you make the preprocessing results available for direct download?

Thank you so much!

**Comment by yanwei-li** [comment]
Hi, I share the preprocessed file [here](https://drive.google.com/drive/folders/1fjWyRhLd8vG5EOEp1Ydkuh5gEbHwT-WW?usp=sharing). Maybe you can try it. But please make sure the data path is set to ```./data/nuscenes```.

**Comment by GondorFu** [comment]
> Hi, I share the preprocessed file [here](https://drive.google.com/drive/folders/1fjWyRhLd8vG5EOEp1Ydkuh5gEbHwT-WW?usp=sharing). Maybe you can try it. But please make sure the data path is set to `./data/nuscenes`.

According to your preprocessing code, after generate the pkl files, the code run the create_groundtruth_database function. Actually, this is the most time-consuming part. It seems generate the data/nuscenes/nuscenes_unified_gt_database floder, wouldn't these be used in training?

**Comment by yanwei-li** [comment]
This is used for modality fusion and lidar-based settings. Please ignore it if you already have generated GT database before or you only want to test on camera-based settings.
