### ISSUE TITLE
Question about traning time and inference time?

### ISSUE THREAD

**Issue by sinsin1998** [dvlab-research/UVTR#20]
There is no information about the flops in your great work, could you tell me how many time you use to train this model , the graphics card you select and the flops? 
Thanks a lot!

**Comment by yanwei-li** [comment]
Hi, for inference time, please refer to Table 13 in the appendix of the updated version (https://arxiv.org/pdf/2206.00630.pdf). For training time, it costs about 2 days for R50 backbone (camera-based setting) in V100 GPU.

**Comment by sinsin1998** [comment]
OK thanks  a lot!
