### ISSUE TITLE
How to compute heights Z in voxel space?

### ISSUE THREAD

**Issue by shb9793** [dvlab-research/UVTR#21]
Excuse me, I didn't understand the core of following table in your paper. 
![image](https://user-images.githubusercontent.com/73088593/201887049-3f1c890e-adb6-4e64-8b9e-ce8613d13b18.png)

Could you please explain how to compute heights Z in voxel space, such as h=5 or h=11.
Looking forward to your early reply. Thanks a lot!

**Comment by yanwei-li** [comment]
Hi, the ```height``` here indicates number of the sampling points in voxel space construction. For example, the ```Z``` of image voxel space in Figure 3 of the main paper is set to 5 if we use ```h=5```.

**Comment by shb9793** [comment]
Thanks a lot for your clear explanation!
