### ISSUE TITLE
Gpu memory exceeded when training a a model

### ISSUE THREAD

**Issue by pyz-creeper** [dvlab-research/UVTR#25]
Hi, thanks for the great work. I was experimenting on an adversarial training method using your multi-modality model, but the gpu memory ran out very quickly. Can you share roughly how much gpu memory is required to train the model assuming the batch size is one?

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. For the largest model LiDAR-V0075-R101, I used the A100, it may cost about 64G with Batch size 2. That means about 32G if the batch size is set to 1. 
If you do not need to train it from scratch, it's better to fix the pre-trained model, which reduces the cost a lot.

**Comment by pyz-creeper** [comment]
> Hi, thanks for your interest. For the largest model LiDAR-V0075-R101, I used the A100, it may cost about 64G with Batch size 2. That means about 32G if the batch size is set to 1. If you do not need to train it from scratch, it's better to fix the pre-trained model, which reduces the cost a lot.

Thanks for your reply, I am going to try it with a bigger gpu.
