### ISSUE TITLE
KeyError: 'cam_sweeps_info'

### ISSUE THREAD

**Issue by tangtaogo** [dvlab-research/UVTR#3]
Hi,
Tanks for your excellent work!
But I confuse with the **cam_sweeps_info** in **NuScenesSweepDataset** [cam_sweeps_info](https://github.com/dvlab-research/UVTR/blob/2f1945f1ba36f4a755c5a8ff40ab07235d0f50b9/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py#L269).  Where did it get it from？

**Comment by yanwei-li** [comment]
Hi, Thanks for your interest. This is our defined info with multiple camera sweeps. You can generate it following the step in README like this:
```
python3 extra_tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes_unified
```

**Comment by tangtaogo** [comment]
Thanks for your kind reply!
