### ISSUE TITLE
About the verison of mmdet3d

### ISSUE THREAD

**Issue by qzhang852** [dvlab-research/UVTR#30]
Dear Author,
I wonder if your given weights is finsihed with mmDetection3D v0.17.3, since when I test it on nuscenes eval with v1.0.0rc5. The performace got crashed with mAP: 0.1344. I guessed the new weight file trained with mmdet3d 1.0 is requried and do you have a new weight when mmdet3d v1.0? Thank you in advance.

**Comment by yanwei-li** [comment]
Hi,
Thanks for your interest! Because I don't have enough resources to train it from scratch now. You can try v0.17.3 for the inference. I guess the mismatch is caused by the coordinate change in new version. Of course, if you train it using v1.0.0rc5, it should achieve the correct results. Thanks!
