### ISSUE TITLE
could you please provide your training log?

### ISSUE THREAD

**Issue by yy9996** [dvlab-research/UVTR#5]
rt,thanks.

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. Could you tell me which experiment log you need? Because the previous used workspace is deleted, and only the trained models are preserved. But I'll train the specific model you need again.

**Comment by yy9996** [comment]
uvtr_l2c_r101_h11.py ，very appreciated.

**Comment by yanwei-li** [comment]
No problem. I'll update the results here once finished.

**Comment by yanwei-li** [comment]
Hi, sorry for the late reply. Here is the running log for [UVTR-L2C-R101-H11](https://drive.google.com/file/d/1BO2_Hhy8ZjevoFftEQM7tyiXx_V0vC8S/view?usp=sharing), because the PyTorch and the mmdet3D version is updated to 1.11 and v1.0, the performance may have some variance. Hope it could help you.

**Comment by yy9996** [comment]
谢谢兄弟。
