### ISSUE TITLE
mmdet3d version problem

### ISSUE THREAD

**Issue by YongtaoGE** [dvlab-research/UVTR#8]
Hi, thanks for you work. I found this project is based on mmdet 0.17. I want to know if I use mmdet > 1.0, will I need to modify the code?  mmdet3d > 1.0 seems have changed the coordinate system.

**Comment by yanwei-li** [comment]
Yes, you are right. It is suggested to use mmdet3d v0.17 for testing. If you use v1.x, due to the change in coordinate system, you need to change the code in 1. data info preparation, 2. nuscenes dataset, 3. box conversion in output.

**Comment by YongtaoGE** [comment]
Hi, thanks for your reply. It is appreciated if you could provide a code snippet for the box conversion in output. I found that it seems you already have trained your code in 1.0x in another [issue](https://github.com/dvlab-research/UVTR/issues/5#issuecomment-1197727735).

**Comment by yanwei-li** [comment]
Sorry for the late reply. I have merged the modification to support mmdet3d v1.x. Please try it again~

**Comment by YongtaoGE** [comment]
@yanwei-li  Thanks for your update. It really helps.

**Comment by yanwei-li** [comment]
Hi @YongtaoGe, I also update the data converter. You may need to regenerate the data info in mmdet v1.x following this 
```
python3 extra_tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes_unified
```

**Comment by YongtaoGE** [comment]
Thanks @yanwei-li. I will have a try.
